"""
NetSage AI  -  Batch AI Evaluation

Implements workflow step 4 of the project brief:

    "Run AI diagnosis: Feed each case to the AI assistant. Save the response
     and compare it with the known correct answer."

For every case in the database this runs the diagnosis engine, stores the
diagnosis, and scores the prediction against the ground-truth `concept` and
`osi_layer` from cases.csv:

    MATCH     concept and OSI layer both correct
    PARTIAL   one of the two correct
    MISMATCH  neither correct

The per-case table and the summary are written to docs/AI_EVALUATION.md and
data/ai_evaluation.csv, and returned for the seeder / dashboard to consume.
"""

import os
import csv
import io
import contextlib
from typing import Dict, Any, List

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPORT_MD = os.path.join(ROOT, "docs", "AI_EVALUATION.md")
REPORT_CSV = os.path.join(ROOT, "data", "ai_evaluation.csv")


def _norm_layer(value: str) -> str:
    """'Layer 3 (Network)' -> 'layer 3'."""
    return (value or "").split("(")[0].strip().lower()


def evaluate(write_report: bool = True) -> Dict[str, Any]:
    from backend.db import get_all_cases
    from backend.diagnosis_engine import DiagnosisEngine

    engine = DiagnosisEngine()
    cases = get_all_cases()
    rows: List[Dict[str, Any]] = []

    for c in cases:
        with contextlib.redirect_stdout(io.StringIO()):
            d = engine.diagnose(c["symptom"], c["topology_note"], c["show_outputs"], c["case_id"])

        concept_ok = d["concept"].strip().lower() == c["concept"].strip().lower()
        layer_ok = _norm_layer(d["osi_layer"]) == _norm_layer(c["osi_layer"])
        verdict = "MATCH" if (concept_ok and layer_ok) else ("PARTIAL" if (concept_ok or layer_ok) else "MISMATCH")

        rows.append({
            "case_id": c["case_id"],
            "diagnosis_id": d.get("id"),
            "expected_concept": c["concept"],
            "predicted_concept": d["concept"],
            "expected_layer": c["osi_layer"],
            "predicted_layer": d["osi_layer"],
            "concept_ok": concept_ok,
            "layer_ok": layer_ok,
            "verdict": verdict,
            "confidence": d["confidence"],
            "predicted_root_cause": d["root_cause"],
            "expected_fault": c["expected_fault"],
        })

    total = len(rows) or 1
    summary = {
        "total": len(rows),
        "match": sum(r["verdict"] == "MATCH" for r in rows),
        "partial": sum(r["verdict"] == "PARTIAL" for r in rows),
        "mismatch": sum(r["verdict"] == "MISMATCH" for r in rows),
        "concept_accuracy": round(sum(r["concept_ok"] for r in rows) / total * 100, 1),
        "layer_accuracy": round(sum(r["layer_ok"] for r in rows) / total * 100, 1),
        "exact_accuracy": round(sum(r["verdict"] == "MATCH" for r in rows) / total * 100, 1),
    }

    if write_report:
        _write_csv(rows)
        _write_md(rows, summary)

    return {"rows": rows, "summary": summary}


def _write_csv(rows: List[Dict[str, Any]]) -> None:
    fields = ["case_id", "expected_concept", "predicted_concept", "expected_layer",
              "predicted_layer", "verdict", "confidence", "predicted_root_cause", "expected_fault"]
    with open(REPORT_CSV, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)


def _write_md(rows: List[Dict[str, Any]], summary: Dict[str, Any]) -> None:
    lines = [
        "# NetSage AI  -  Batch AI Evaluation Report",
        "",
        "_Auto-generated by `backend/evaluate.py` (run during seeding). Every case in "
        "`cases.csv` is fed to the offline diagnosis engine and the prediction is compared "
        "against the known-correct `concept` and `osi_layer`._",
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|---|---|",
        f"| Cases evaluated | {summary['total']} |",
        f"| Exact match (concept + OSI layer) | {summary['match']} ({summary['exact_accuracy']}%) |",
        f"| Partial (one of two correct) | {summary['partial']} |",
        f"| Mismatch (neither correct) | {summary['mismatch']} |",
        f"| Concept accuracy | {summary['concept_accuracy']}% |",
        f"| OSI-layer accuracy | {summary['layer_accuracy']}% |",
        "",
        "The PARTIAL and MISMATCH rows are the cases a human reviewer corrected  -  see "
        "`RESPONSIBLE_AI.md` and the Responsible AI Log in the dashboard.",
        "",
        "## Per-case results",
        "",
        "| Case | Verdict | Predicted (concept / layer) | Expected (concept / layer) | AI confidence |",
        "|---|---|---|---|---|",
    ]
    order = {"MISMATCH": 0, "PARTIAL": 1, "MATCH": 2}
    for r in sorted(rows, key=lambda x: (order[x["verdict"]], x["case_id"])):
        lines.append(
            f"| {r['case_id']} | {r['verdict']} | {r['predicted_concept']} / "
            f"{_norm_layer(r['predicted_layer']).title()} | {r['expected_concept']} / "
            f"{_norm_layer(r['expected_layer']).title()} | {r['confidence']} |"
        )
    lines.append("")
    with open(REPORT_MD, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    import sys
    sys.path.insert(0, ROOT)
    from backend.db import init_db
    init_db()
    result = evaluate(write_report=True)
    s = result["summary"]
    print(f"Evaluated {s['total']} cases: {s['match']} match, {s['partial']} partial, "
          f"{s['mismatch']} mismatch")
    print(f"Concept accuracy {s['concept_accuracy']}%  |  OSI-layer accuracy {s['layer_accuracy']}%  "
          f"|  exact {s['exact_accuracy']}%")
    print(f"Report: {REPORT_MD}")
